# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CreatePDF' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CreatePDF

# https://github.com/techprimate/TPPDF.git
pod 'TPPDF'
end
